import Head from 'next/head'
import Image from 'next/image'
import React, {useState} from 'react'
import firebaseClient from 'firebase/client';
import {useCollection} from 'react-firebase-hooks/firestore'
import Auth from 'components/Auth'
import Wish from '@/components/Wish'


export default function Home({currentUser}) {

  const [whishes, whishesLoading , whishesError] = useCollection(
    firebaseClient.firestore().collection('wishes'),{}
  )

  const[wish,setWish] = useState<string>("");

  const addWish = async () => { 
    if(wish.length> 0 ) {
      await firebaseClient.firestore().collection('wishes').doc(currentUser.uid).set({wish});
    }
    setWish("")
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-4">
        {!currentUser && <Auth />}
        {currentUser && (
          <>
          <h1 className="mb-6 text-white font-semibold text-3xl uppercase">do you have{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-br from-green-700  to-yellow-400">something</span>
          {" "}to say?
          </h1>

          <div className="flex space-x-4 mb-6">
            <input type="text" placeholder="My comment..." value={wish} 
            onChange={(event) => {setWish(event.target.value)}}
            className="px-3 py-3 placeholder-green-500 relative bg-white rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring-2 w-full"/>
            <button className="bg-transparent text-white font-semibold hover:text-blue-400 py-2 px-4 border border-blue-500 hover:border-blue-700 rounded"
            onClick={addWish}
            >
              Send</button>

          </div>
            <div>
              {whishes?.docs.map(doc => (
                <Wish key={doc.id} wish={doc.data().wish} userId={doc.id}/>
              )) }
            </div>
          </>
        )}
      </main>
       
    </div>
  )
}
